version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbmotchillPG
      ports:
        - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Giúp lưu trữ dữ liệu

volumes:
  postgres_data:
