version: "3.8"
services:
  db:
    image: postgres
    container_name: motchillPG_CK
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbmotchillCK
    ports:
      - "5432:5432" # Đảm bảo là chuỗi, bao gồm dấu ngoặc kép
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
